export default {
  background: '#efefef',
  text: '#4e4b4b',
  invertedText: 'white',
  hintText: '#958a8a',
  headingText: '#4e4b4b',
  placeholderText: '#bcbcbc',
  inputBackground: '#FFFFFF',
  blockBackground: '#FFFFFF',
  iconColor: '#bdbdbd',
  primary: '#007aff',
  danger: '#ff6f59',
  normal: '#ffffff',
  info: '#9cc0ff',
  light: '#efefef',
  blockTitle: '#d8d8d8',
}
